# Generated by Django 3.2.16 on 2023-05-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=15, verbose_name='Текст комментария'),
        ),
    ]
